kind: pipeline
type: docker
name: build

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone http://gitea.burkcules.burke/burke/budget-api.git
      - cd budget-api/
      - git checkout $DRONE_COMMIT
    
  - name: build
    image: bitnami/dotnet-sdk
    commands:
      - cd budget-api/BudgetApi
      - dotnet publish --configuration Release

  - name: set-secrets-stage
    image: bitnami/dotnet-sdk
    commands:
      - cd budget-api/BudgetApi/bin/Release/net5.0/publish
      - set Budget:DbServer=$DB_SERVER_STAGE
      - set Budget:DbUser=$DB_USER_STAGE
      - set Budget:DbPassword=$DB_PASSWORD_STAGE
    when:
      branch:
        - stage

  - name: set-secrets-prod
    image: bitnami/dotnet-sdk
    commands:
      - cd budget-api/BudgetApi/bin/Release/net5.0/publish
      - set Budget:DbServer=$DB_SERVER_PROD
      - set Budget:DbUser=$DB_USER_PROD
      - set Budget:DbPassword=$DB_PASSWORD_PROD
    when:
      branch:
        - master

  - name: test
    image: bitnami/dotnet-sdk
    commands:
      - echo "figure out how to write and run tests on an EF Core Api"

  - name: deploy-stage
    image: appleboy/drone-scp
    settings:
      host: 192.168.1.12
      username:
        from_secret: SSH_USER
      password:
        from_secret: SSH_PASSWORD
      port: 22
      target: /var/www/budget-api
      source: ./budget-api/BudgetApi/bin/Release/net5.0/publish/*
      strip_components: 6
      rm: true
    when:
      branch:
        - stage
    
  - name: deploy-prod
    image: appleboy/drone-scp
    settings:
      host: 192.168.1.20
      username:
        from_secret: SSH_USER_PROD
      password:
        from_secret: SSH_PASSWORD_PROD
      port: 22
      target: /var/www/budget-api
      source: ./budget-api/BudgetApi/bin/Release/net5.0/publish/*
      strip_components: 6
      rm: true
    when:
      branch:
        - master

  - name: restart-service-stage
    image: appleboy/drone-scp
    settings:
      host: 192.168.1.12
      username:
        from_secret: SSH_USER_STAGE
      password:
        from_secret: SSH_PASSWORD_STAGE
      port: 22
      command_timeout: 2m
      script:
        - service budget-api restart
    when:
      branch:
        - stage

  - name: restart-service-prod
    image: appleboy/drone-scp
    settings:
      host: 192.168.1.20
      username:
        from_secret: SSH_USER_STAGE
      password:
        from_secret: SSH_PASSWORD_STAGE
      port: 22
      command_timeout: 2m
      script:
        - service budget-api restart
    when:
      branch:
        - master

trigger:
  branch:
    - stage
    - master
  event:
    - push