kind: pipeline
type: docker
name: build

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone http://gitea.burkcules.burke/burke/budget-api.git
      - cd budget-api/
      - git checkout $DRONE_COMMIT
    
  - name: build-stage
    image: bitnami/dotnet-sdk
    environment:
      DB_SERVER:
        from_secret: DB_SERVER_STAGE
      DB_USER:
        from_secret: DB_USER_STAGE
      DB_PASSWORD:
        from_secret: DB_PASSWORD_STAGE
    commands:
      - cd budget-api/BudgetApi
      - dotnet publish --configuration Release
    when:
      branch:
        - stage

  - name: build-prod
    image: bitnami/dotnet-sdk
    environment:
      DB_SERVER:
        from_secret: DB_SERVER_PROD
      DB_USER:
        from_secret: DB_USER_PROD
      DB_PASSWORD:
        from_secret: DB_PASSWORD_PROD
    commands:
      - cd budget-api/BudgetApi
      - dotnet publish --configuration Release
    when:
      branch:
        - master

  - name: test
    image: bitnami/dotnet-sdk
    commands:
      - echo "figure out how to write and run tests on an EF Core Api"

  - name: deploy-stage
    image: appleboy/drone-scp
    settings:
      host: 192.168.1.12
      username:
        from_secret: SSH_USER
      password:
        from_secret: SSH_PASSWORD
      port: 22
      target: /var/www/budget-api
      source: ./budget-api/BudgetApi/bin/Release/net5.0/publish/*
      strip_components: 6
      rm: true
    when:
      branch:
        - stage
    
  - name: deploy-prod
    image: appleboy/drone-scp
    settings:
      host: 192.168.1.20
      username:
        from_secret: SSH_USER_PROD
      password:
        from_secret: SSH_PASSWORD_PROD
      port: 22
      target: /var/www/budget-api
      source: ./budget-api/BudgetApi/bin/Release/net5.0/publish/*
      strip_components: 6
      rm: true
    when:
      branch:
        - master

  - name: restart-service-stage
    image: appleboy/drone-ssh
    settings:
      host: 192.168.1.12
      username:
        from_secret: SSH_USER
      password:
        from_secret: SSH_PASSWORD
      port: 22
      script:
        - sudo systemctl restart budget-api.service
    when:
      branch:
        - stage

  - name: restart-service-prod
    image: appleboy/drone-ssh
    settings:
      host: 192.168.1.20
      username:
        from_secret: SSH_USER_PROD
      password:
        from_secret: SSH_PASSWORD_PROD
      port: 22
      script:
        - sudo systemctl restart budget-api.service
    when:
      branch:
        - master

trigger:
  branch:
    - stage
    - master
  event:
    - push